services:
  notepad:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-text-bin
    container_name: simple-text-bin
    environment:
      - SECRET_KEY=abcx
    ports:
      - "8099:80"
    volumes:
      - ./data-test.txt:/var/www/html/data.txt   # Mount personal txt file
    restart: always