name = "quick-note"
main = "worker.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "QUICK_NOTE"
id = "your_kv_id"      #REQUIRED

[[routes]] #OPTIONAL
pattern = "your.domain.com"
custom_domain = true
