name: Docker Compose Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Đây là dòng quan trọng để kích hoạt nút bấm thủ công

jobs:
  test-app-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: cd docker && docker compose up -d --build

      - name: Check Health 200
        run: |
          sleep 5
          # Kiểm tra xem container có phản hồi HTTP 200 không
          curl -I http://localhost:8099/?secret=abcx | grep -q "HTTP/1.1 200"

      - name: Check Health 401
        run: |
          sleep 5
          # Kiểm tra xem container có phản hồi HTTP 401 không
          curl -I http://localhost:8099/ | grep -q "HTTP/1.1 401"
